import { Component } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { TranslatePipe } from '@ngx-translate/core';
import { AuthService } from '../../../core/services/auth.service';
import { UiButtonComponent } from '../../../shared/components/ui-button/ui-button.component';
import { UiInputComponent } from '../../../shared/components/ui-input/ui-input.component';
@Component({
  selector: 'app-register',
  imports: [ReactiveFormsModule, RouterLink, TranslatePipe, UiButtonComponent, UiInputComponent],
  template: `<section class="app-shell grid min-h-[calc(100vh-9rem)] items-center gap-6 lg:grid-cols-[1.1fr_.9fr]">
  <form [formGroup]="form" (ngSubmit)="submit()" class="card mx-auto w-full max-w-xl space-y-5 p-6 md:p-8"><div><p class="text-sm font-black uppercase tracking-wide text-rose-500">{{ 'AUTH.START' | translate }}</p><h1 class="mt-2 text-3xl font-black">{{ 'AUTH.REGISTER' | translate }}</h1><p class="mt-2 text-slate-500">{{ 'AUTH.REGISTER_TEXT' | translate }}</p></div><div class="grid gap-4 md:grid-cols-2"><app-ui-input [control]="form.controls.name" [label]="'AUTH.NAME' | translate" /><app-ui-input [control]="form.controls.email" [label]="'AUTH.EMAIL' | translate" /></div><div class="grid gap-4 md:grid-cols-2"><app-ui-input [control]="form.controls.password" type="password" [label]="'AUTH.PASSWORD' | translate" /><app-ui-input [control]="form.controls.password_confirmation" type="password" [label]="'AUTH.CONFIRM' | translate" /></div><label class="block text-sm font-bold text-slate-700"><span class="mb-2 block">{{ 'AUTH.ROLE' | translate }}</span><select formControlName="role" class="field"><option value="guest">{{ 'AUTH.GUEST' | translate }}</option><option value="host">{{ 'AUTH.HOST' | translate }}</option></select></label>@if (error) { <p class="rounded-2xl bg-rose-50 px-4 py-3 text-sm font-bold text-rose-700">{{ error }}</p> }<app-ui-button type="submit" [disabled]="form.invalid">{{ 'AUTH.REGISTER' | translate }}</app-ui-button><p class="text-center text-sm font-semibold text-slate-500">{{ 'AUTH.HAS_ACCOUNT' | translate }} <a routerLink="/login" class="font-black text-rose-600">{{ 'AUTH.LOGIN' | translate }}</a></p></form>
  <div class="relative hidden min-h-[620px] overflow-hidden rounded-[2.5rem] bg-gradient-to-br from-rose-500 to-orange-400 p-8 text-white shadow-2xl shadow-rose-500/20 lg:block"><div class="absolute -right-16 top-10 h-56 w-56 rounded-full bg-white/20 blur-2xl"></div><div class="relative flex h-full flex-col justify-between"><span class="pill border-white/20 bg-white/15 text-white">Host ready</span><div><h2 class="text-5xl font-black leading-tight">{{ 'AUTH.HOST_CTA' | translate }}</h2><p class="mt-4 text-white/80">{{ 'AUTH.HOST_TEXT' | translate }}</p></div></div></div>
</section>`
})
export class RegisterComponent { error = ''; form = new FormBuilder().nonNullable.group({ name: ['', Validators.required], email: ['', [Validators.required, Validators.email]], password: ['', Validators.required], password_confirmation: ['', Validators.required], role: ['guest', Validators.required] }); constructor(private auth: AuthService, private router: Router) {} submit(): void { this.auth.register(this.form.getRawValue()).subscribe({ next: () => this.router.navigateByUrl('/'), error: e => this.error = e.error?.message || 'Error' }); } }
